import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const { exam, level, hours, months } = await request.json();

    if (!exam || !level || !hours || !months) {
      return NextResponse.json({ error: 'Missing parameters' }, { status: 400 });
    }

    const hoursNum = parseInt(hours) || 4;
    const monthsNum = parseInt(months) || 6;

    const apiKey = process.env.OPENROUTER_API_KEY;
    if (apiKey && apiKey !== '<your-openrouter-key>' && !apiKey.startsWith('<')) {
      try {
        const prompt = `You are an expert academic mentor for the CareerVerse AI platform.
Generate a comprehensive, actionable study plan for a student preparing for the "${exam}" exam.
Student Profile:
- Current Level: ${level}
- Time Commitment: ${hoursNum} hours per day
- Time until Exam: ${monthsNum} months

Output a structured markdown plan. Include:
1. An overall strategy overview.
2. A phase-by-phase breakdown (e.g., Phase 1: Foundation, Phase 2: Core, Phase 3: Mock & Revision).
3. A sample daily timetable based on the ${hoursNum} hours provided.
4. Top 3 pro-tips for this specific exam.
Keep the formatting clean with markdown headings (##, ###) and bullet points.`;

        const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": "http://localhost:3000",
            "X-Title": "CareerVerse AI"
          },
          body: JSON.stringify({
            model: "google/gemini-2.5-flash:free",
            messages: [
              { role: "system", content: "You are an expert study planner and academic mentor." },
              { role: "user", content: prompt }
            ]
          }),
          signal: AbortSignal.timeout(8000)
        });

        if (response.ok) {
          const data = await response.json();
          const plan = data.choices?.[0]?.message?.content;
          if (plan) {
            return NextResponse.json({ plan });
          }
        }
      } catch (apiError) {
        console.error("Study Planner API call failed, falling back to local generator:", apiError);
      }
    }

    // Dynamic High-Quality Local Study Planner Fallback
    const plan = `## Personalized Study Plan for ${exam}
*Generated by PathFinder Study Assistant (Local Engine)*

You are preparing at an **${level}** level with **${hoursNum} hours per day** available for **${monthsNum} months**. Here is your customized study blueprint:

---

### 📅 Phase 1: Foundation & Core Syllabus (Months 1 to ${Math.max(1, Math.round(monthsNum * 0.4))})
- **Focus:** Build solid conceptual clarity, cover high-weightage topics, and resolve core doubts.
- **Weekly Goal:** Study at least ${hoursNum * 6} hours per week. Read basic textbooks and university sheets.
- **Task List:**
  - Create formula sheets and summarize core definitions.
  - Solve chapter-end problems right after reading.
  - Review weaker subjects twice a week.

### 📈 Phase 2: Intensive Practice & Sectional Mocks (Months ${Math.max(1, Math.round(monthsNum * 0.4)) + 1} to ${Math.max(1, Math.round(monthsNum * 0.85))})
- **Focus:** Solve previous year question papers (PYQs), analyze accuracy rates, and work on weak chapters.
- **Weekly Goal:** Take 1 sectional test and 1 practice test every weekend.
- **Task List:**
  - Build speed using short-cut tricks (for quantitative/formula exams).
  - Categorize errors into 'conceptual error' vs 'silly mistake'.
  - Aim for an accuracy of at least 80% on standard questions.

### 🏆 Phase 3: Full-Length Mocks & Revision (Final Month)
- **Focus:** Pure revision, mock tests under exact exam timings, and managing mental composure.
- **Weekly Goal:** Take 2 full-length timed mock tests. Spend 3 hours analyzing each test.
- **Task List:**
  - Revise your custom formula sheet and mistakes notebook daily.
  - Do NOT start any new topics in the last 15 days.
  - Adjust sleep schedule to align with the actual exam timing.

---

### ⏰ Recommended Daily Schedule (${hoursNum} Hours Available)
- **0.5 Hour:** Active Recall / Revision of the previous day's topics.
- **${(hoursNum * 0.55).toFixed(1)} Hours:** Direct Syllabus Study (high-weightage chapters).
- **${(hoursNum * 0.35).toFixed(1)} Hours:** Practice problems, MCQs, or short test reviews.
- **0.5 Hour:** Error analysis and logging notes.

### 💡 Pro-Tips for ${exam} Success
1. **Maintain a Mistakes Notebook:** Write down every MCQ you get wrong, the correct logic, and the relevant concept. Revise this notebook before every test.
2. **Prioritize Data & PYQs:** competitive exams in India repeat formats. Solving the past 10-15 years papers is more valuable than reading 5 different reference books.
3. **Control Exam Stress:** Timed practice helps you build muscle memory. Start taking timed assessments early, not just in the final month.`;

    return NextResponse.json({ plan });
  } catch (error: any) {
    console.error('Study Planner API error:', error);
    return NextResponse.json(
      { error: 'Failed to generate plan', details: error.message },
      { status: 500 }
    );
  }
}
